# Standalone build for the published repo. Generated by
# platform/tangled/publish/gen-project.nu; edit that template, not this file.
#
# The build, the devshell and its hooks, the formatter and the nixpkgs this
# resolves against are shared with every other repo published from the
# monorepo, and live in the nix-workspace flake. It is callable, so what is
# particular to this project is all that is left to say.
{
  description = "A pkg-config-compatible build metadata tool written in Rust";

  inputs.workspace.url = "git+https://tangled.org/overby.me/nix-workspace";

  outputs = inputs:
    inputs.workspace ./. {
      name = "oxidized-pkg-config";
      description = "A pkg-config-compatible build metadata tool written in Rust";
      aliases = {
        "pkg-config" = "pkgconf";
      };
      setupHook = "setup-hook.sh";
    };
}
